AllCops:
  Include:
    - Rakefile
  Exclude:
    - spec/dummy/db/**/*
    - spec/dummy/bin/**/*
    - tmp/**/*
    - spec/dummy/config/initializers/devise.rb
    - lib/generators/redde/scaffold/templates/controllers/controller.rb
Rails:
  Enabled: true
Documentation:
  Enabled: false
LineLength:
  Max: 150
Style/AlignHash:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
