script: bundle exec rspec
language: ruby
services:
  - redis-server
notifications:
  email: false
rvm:
  - 2.3
  - 2.4
before_install:
  - gem install bundler
before_script:
  - 'bundle exec rake db:setup RAILS_ENV=test'
